\ @file boot/offsets.sp
\ DO NOT EDIT MANUALLY! THIS FILE WAS GENERATED BY: boot/make.py
\
\ @brief Defines global variable offsets.

\ struct Slc { ... }
#00   #0=Slc_dat               \ Ref: data
#04   #0=Slc_len               \ U2: length of buffer

\ struct Globals { ... }
#00   #90=G_glen                \ U2
#02   #90=G_gcap                \ U2
#04   #A0=G_fb                  \ &Fiber: current fiber
#0A   #90=G_cstate              \ U2: compiler state
#0C   #80=G_fnState             \ U1: function compilation state
#0D   #80=G_localOffset         \ U1: current offset of locals
#0E   #80=G_logLvlSys           \ U1
#0F   #80=G_logLvlUsr           \ U1
#08   #90=G_metaNext            \ U2: next function's meta
#10   #A0=G_curNode             \ Ref: current compiling dict node
#14   #A0=G_compFn              \ Ref: function used for compiling
#18   #A0=G_bbaLocal            \ BBA: local BBA
#24   #A0=G_dictLocal           \ &DNode: local dict
#28   #A0=G_bbaPub              \ &BBA: current public bba
#2C   #A0=G_bbaPriv             \ &BBA: current private bba
#34   #A0=G_dictStk             \ Stk: stack of dictionary references
#3C   #A0=G_srcM                \ &FileMethods: src file methods
#40   #A0=G_src                 \ &File: src File

\ struct File { ... }
#08   #0=Fs_buf                \ Buf: buffer
#10   #0=Fs_plc                \ U2: plc in buffer

\ BBA methods:
#00   #0=BBAm_bump             \ method index
#01   #0=BBAm_newBlock         \ method index
#02   #0=BBAm_drop             \ method index

\ struct DNode { ... }
#00   #0=DN_l                  \ Ref: left
#04   #0=DN_r                  \ Ref: right
#08   #0=DN_ckey               \ Ref: counted data key
#10   #0=DN_m                  \ U2: meta
#0C   #0=DN_v                  \ Ref: value, which may be a constant
#14   #0=DN_ty                 \ Ref?: only exists if C_TYPED

