\ @file kernel/globals.sp
\ DO NOT EDIT MANUALLY! THIS FILE WAS GENERATED BY: etc/make.py
\
\ @brief Defines global variable offsets.

\ Kernel Data. Note: raw references, not global offsets
#04  #0=k_memTop
#2C  #0=k_dict

\ Kernel Global Offsets
#06  #0=k_err
#00  #0=k_glen
#02  #0=k_gcap
#08  #0=k_curBBA
#10  #0=k_src

