\ @file kernel/globals.sp
\ DO NOT EDIT MANUALLY! THIS FILE WAS GENERATED BY: etc/make.py
\
\ @brief Defines global variable offsets.

\ Kernel Data. Note: raw references, not global offsets
#04  #0=k_memTop
#08  #0=k_ba
#14  #0=k_bba
#20  #0=k_bbaTmp
#2C  #0=k_dict

\ Kernel Global Offsets
#02  #0=k_err
#04  #0=k_gbuf
#0C  #0=k_curBBA
#14  #0=k_src

